/*
  Warnings:

  - You are about to drop the column `priviledges` on the `admin` table. All the data in the column will be lost.
  - You are about to drop the column `role` on the `staff` table. All the data in the column will be lost.

*/
-- CreateEnum
CREATE TYPE "priviledges" AS ENUM ('VIEW_ALL_SCHOOLS', 'MANAGE_SCHOOLS', 'SYSTEM_CONFIGURATION', 'VIEW_ALL_SCHOOL_DETAILS', 'VIEW_SELF_SCHOOL_DETAILS', 'EDIT_ALL_SCHOOL_DETAILS', 'EDIT_SELF_SCHOOL_DETAILS', 'MANAGE_ALL_SCHOOL_USERS', 'MANAGE_SELF_SCHOOL_USERS', 'VIEW_ALL_CLASSES', 'VIEW_SELF_CLASSES', 'MANAGE_ALL_CLASSES', 'MANAGE_SELF_CLASSES', 'VIEW_ALL_STREAMS', 'VIEW_SELF_STREAMS', 'MANAGE_ALL_STREAMS', 'MANAGE_SELF_STREAMS', 'VIEW_ALL_USER_PROFILES', 'VIEW_SELF_USER_PROFILE', 'EDIT_ALL_USER_PROFILES', 'EDIT_SELF_USER_PROFILE', 'RESET_ALL_USER_PASSWORDS', 'RESET_SELF_USER_PASSWORD', 'VIEW_ALL_STAFF_PROFILES', 'VIEW_SELF_STAFF_PROFILE', 'EDIT_ALL_STAFF_PROFILES', 'EDIT_SELF_STAFF_PROFILE', 'RESET_ALL_STAFF_PASSWORDS', 'RESET_SELF_STAFF_PASSWORD', 'VIEW_ALL_TEACHER_PROFILES', 'VIEW_SELF_TEACHER_PROFILE', 'EDIT_ALL_TEACHER_PROFILES', 'EDIT_SELF_TEACHER_PROFILE', 'RESET_ALL_TEACHER_PASSWORDS', 'RESET_SELF_TEACHER_PASSWORD', 'VIEW_ALL_PARENT_PROFILES', 'VIEW_SELF_PARENT_PROFILE', 'EDIT_ALL_PARENT_PROFILES', 'EDIT_SELF_PARENT_PROFILE', 'RESET_ALL_PARENT_PASSWORDS', 'RESET_SELF_PARENT_PASSWORD', 'VIEW_ALL_EXAMS', 'VIEW_SELF_EXAMS', 'CREATE_EXAMS', 'EDIT_ALL_EXAMS', 'EDIT_SELF_EXAMS', 'GRADE_ALL_EXAMS', 'GRADE_SELF_EXAMS', 'VIEW_ALL_EXAM_RESULTS', 'VIEW_SELF_EXAM_RESULTS', 'VIEW_PERSONAL_RESULTS', 'SUBMIT_ASSIGNMENTS', 'VIEW_ALL_COURSE_MATERIALS', 'VIEW_SELF_COURSE_MATERIALS', 'MANAGE_ALL_COURSE_MATERIALS', 'MANAGE_SELF_COURSE_MATERIALS', 'TAKE_ALL_ATTENDANCE', 'TAKE_SELF_ATTENDANCE', 'VIEW_ALL_ATTENDANCE', 'VIEW_SELF_ATTENDANCE', 'VIEW_ALL_FINANCIAL_RECORDS', 'VIEW_SELF_FINANCIAL_RECORDS', 'MANAGE_ALL_FINANCIAL_RECORDS', 'MANAGE_SELF_FINANCIAL_RECORDS', 'VIEW_PERSONAL_FINANCIAL_INFO');

-- AlterTable
ALTER TABLE "admin" DROP COLUMN "priviledges";

-- AlterTable
ALTER TABLE "staff" DROP COLUMN "role";

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role_id" INTEGER;

-- DropEnum
DROP TYPE "priviledges_available";

-- CreateTable
CREATE TABLE "permission" (
    "permission_id" SERIAL NOT NULL,
    "priviledges" "priviledges" NOT NULL,
    "role_id" INTEGER,

    CONSTRAINT "permission_pkey" PRIMARY KEY ("permission_id")
);

-- CreateTable
CREATE TABLE "role" (
    "role_id" SERIAL NOT NULL,
    "role" VARCHAR(50) NOT NULL,

    CONSTRAINT "role_pkey" PRIMARY KEY ("role_id")
);

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "permission" ADD CONSTRAINT "permission_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "role"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
