-- AlterTable
ALTER TABLE "users" ALTER COLUMN "name" SET DATA TYPE VARCHAR(250),
ALTER COLUMN "first_name" SET DATA TYPE VARCHAR(250),
ALTER COLUMN "last_name" SET DATA TYPE VARCHAR(250),
ALTER COLUMN "id_code" SET DATA TYPE VARCHAR(230),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "phone" SET DATA TYPE VARCHAR(220);
