/*
  Warnings:

  - The values [VIEW_ALL_SCHOOLS,MANAGE_SCHOOLS,SYSTEM_CONFIGURATION,VIEW_ALL_SCHOOL_DETAILS,VIEW_SELF_SCHOOL_DETAILS,EDIT_ALL_SCHOOL_DETAILS,EDIT_SELF_SCHOOL_DETAILS,MANAGE_ALL_SCHOOL_USERS,MANAGE_SELF_SCHOOL_USERS,VIEW_ALL_CLASSES,VIEW_SELF_CLASSES,VIEW_SELF_SCHOOL_CLASSES,MANAGE_ALL_CLASSES,MANAGE_SELF_CLASSES,MANAGE_SELF_SCHOOL_CLASSES,VIEW_ALL_STREAMS,VIEW_SELF_STREAMS,VIEW_SELF_SCHOOL_STREAMS,MANAGE_ALL_STREAMS,MANAGE_SELF_STREAMS,MANAGE_SELF_SCHOOL_STREAMS,VIEW_ALL_USER_PROFILES,VIEW_SELF_USER_PROFILE,VIEW_SELF_SCHOOL_USER_PROFILES,EDIT_ALL_USER_PROFILES,EDIT_SELF_USER_PROFILE,EDIT_SELF_SCHOOL_USER_PROFILES,RESET_ALL_USER_PASSWORDS,RESET_SELF_USER_PASSWORD,RESET_SELF_SCHOOL_USER_PASSWORDS,VIEW_ALL_STAFF_PROFILES,VIEW_SELF_STAFF_PROFILE,VIEW_SELF_SCHOOL_STAFF_PROFILES,EDIT_ALL_STAFF_PROFILES,EDIT_SELF_STAFF_PROFILE,EDIT_SELF_SCHOOL_STAFF_PROFILES,RESET_ALL_STAFF_PASSWORDS,RESET_SELF_STAFF_PASSWORD,RESET_SELF_SCHOOL_STAFF_PASSWORDS,VIEW_ALL_TEACHER_PROFILES,VIEW_SELF_TEACHER_PROFILE,VIEW_SELF_SCHOOL_TEACHER_PROFILES,EDIT_ALL_TEACHER_PROFILES,EDIT_SELF_TEACHER_PROFILE,EDIT_SELF_SCHOOL_TEACHER_PROFILES,RESET_ALL_TEACHER_PASSWORDS,RESET_SELF_TEACHER_PASSWORD,RESET_SELF_SCHOOL_TEACHER_PASSWORDS,VIEW_ALL_PARENT_PROFILES,VIEW_SELF_PARENT_PROFILE,VIEW_SELF_SCHOOL_PARENT_PROFILES,EDIT_ALL_PARENT_PROFILES,EDIT_SELF_PARENT_PROFILE,EDIT_SELF_SCHOOL_PARENT_PROFILES,RESET_ALL_PARENT_PASSWORDS,RESET_SELF_PARENT_PASSWORD,RESET_SELF_SCHOOL_PARENT_PASSWORDS,VIEW_ALL_EXAMS,VIEW_SELF_SCHOOL_EXAMS,VIEW_SELF_EXAMS,CREATE_EXAMS,EDIT_ALL_EXAMS,EDIT_SELF_SCHOOL_EXAMS,EDIT_SELF_CLASS_EXAMS,EDIT_SELF_EXAMS,GRADE_ALL_EXAMS,GRADE_SELF_EXAMS,GRADE_SELF_SCHOOL_EXAMS,GRADE_SELF_CLASS_EXAMS,VIEW_ALL_EXAM_RESULTS,VIEW_SELF_SCHOOL_EXAM_RESULTS,VIEW_SELF_CLASS_EXAMS,VIEW_SELF_EXAM_RESULTS,VIEW_PERSONAL_RESULTS,SUBMIT_ASSIGNMENTS,VIEW_ALL_COURSE_MATERIALS,VIEW_SELF_COURSE_MATERIALS,VIEW_SELF_SCHOOL_COURSE_MATERIALS,VIEW_SELF_CLASS_COURSE_MATERIALS,MANAGE_ALL_COURSE_MATERIALS,MANAGE_SELF_COURSE_MATERIALS,MANAGE_SELF_SCHOOL_COURSE_MATERIALS,MANAGE_SELF_CLASS_COURSE_MATERIALS,TAKE_SELF_SCHOOL_ATTENDANCE,TAKE_SELF_CLASS_ATTENDANCE,TAKE_SELF_ATTENDANCE,VIEW_ALL_ATTENDANCE,VIEW_SELF_SCHOOL_ATTENDANCE,VIEW_SELF_CLASS_ATTENDANCE,VIEW_SELF_ATTENDANCE,VIEW_ALL_FINANCIAL_RECORDS,VIEW_SELF_FINANCIAL_RECORDS,VIEW_SELF_SCHOOL_FINANCIAL_RECORDS,VIEW_SELF_CLASS_FINANCIAL_RECORDS,MANAGE_ALL_FINANCIAL_RECORDS,MANAGE_SELF_FINANCIAL_RECORDS,MANAGE_SELF_SCHOOL_FINANCIAL_RECORDS,MANAGE_SELF_CLASS_FINANCIAL_RECORDS,VIEW_PERSONAL_FINANCIAL_INFO] on the enum `privileges` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "privileges_new" AS ENUM ('admin', 'review', 'update', 'admin_school', 'review_school', 'update_school', 'admin_users', 'update_users', 'review_users', 'admin_events', 'review_events', 'update_events', 'admin_staff', 'admin_students', 'admin_department', 'review_department', 'update_department', 'admin_finance', 'review_finance', 'update_finance', 'admin_exam', 'review_exam', 'update_exam', 'admin_class', 'review_class', 'update_class', 'admin_stream', 'review_stream', 'update_stream', 'review_self', 'update_self');
ALTER TABLE "permission" ALTER COLUMN "privileges" TYPE "privileges_new" USING ("privileges"::text::"privileges_new");
ALTER TYPE "privileges" RENAME TO "privileges_old";
ALTER TYPE "privileges_new" RENAME TO "privileges";
DROP TYPE "privileges_old";
COMMIT;

-- CreateTable
CREATE TABLE "assignment" (
    "assignment_id" SERIAL NOT NULL,
    "description" VARCHAR(100) NOT NULL,
    "teacher_id" INTEGER NOT NULL,
    "subject_id" INTEGER,
    "stream_id" INTEGER,
    "due_date" DATE,

    CONSTRAINT "assignment_pkey" PRIMARY KEY ("assignment_id")
);

-- AddForeignKey
ALTER TABLE "assignment" ADD CONSTRAINT "assignment_teacher_id_fkey" FOREIGN KEY ("teacher_id") REFERENCES "teacher"("teacher_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "assignment" ADD CONSTRAINT "assignment_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "subject"("subject_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "assignment" ADD CONSTRAINT "assignment_stream_id_fkey" FOREIGN KEY ("stream_id") REFERENCES "stream"("stream_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
