-- AlterTable
ALTER TABLE "users" ALTER COLUMN "name" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "first_name" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "last_name" SET DATA TYPE VARCHAR(150),
ALTER COLUMN "id_code" SET DATA TYPE VARCHAR(130),
ALTER COLUMN "phone" SET DATA TYPE VARCHAR(120);
